"""This function was entirely generated by M365 Copilot Think Deeper."""


def rotate(text: str, key: int) -> str:
    """
    Apply a rotational (Caesar) cipher to 'text' using the integer 'key'.
    - Only A–Z and a–z are shifted.
    - Case is preserved.
    - Non-letters (spaces, punctuation, digits) are left unchanged.
    - Keys are normalized with modulo 26 so any integer works.

    Examples (from the exercise README):
      ROT5("omg") -> "trl"
      ROT0("c") -> "c"
      ROT26("Cool") -> "Cool"
      ROT13("The quick brown fox jumps over the lazy dog.") ->
             "Gur dhvpx oebja sbk whzcf bire gur ynml qbt."
    """
    if not isinstance(key, int):
        raise TypeError("key must be an integer")

    shift = key % 26
    if shift == 0:
        return text  # small early exit

    out_chars = []
    for ch in text:
        if 'a' <= ch <= 'z':
            base = ord('a')
            out_chars.append(chr((ord(ch) - base + shift) % 26 + base))
        elif 'A' <= ch <= 'Z':
            base = ord('A')
            out_chars.append(chr((ord(ch) - base + shift) % 26 + base))
        else:
            out_chars.append(ch)
    return ''.join(out_chars)
